//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeVerification
    {
        public int IdEmployeeVerification { get; set; }
        public int IdEmployees { get; set; }
        public System.DateTime StartVerification { get; set; }
        public int IdHRmanager { get; set; }
        public string Fingerprinting { get; set; }
        public string PsychophysiologicalExamination { get; set; }
        public int IdMedicalCommission { get; set; }
        public int IdEmployeeVerificationResult { get; set; }
        public string Note { get; set; }
    
        public virtual EmployeeVerificationResult EmployeeVerificationResult { get; set; }
        public virtual MedicalCommission MedicalCommission { get; set; }
    }
}
