//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRmanager
    {
        public int IdHRmanager { get; set; }
        public int ServiceNumber { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string NumberPhone { get; set; }
        public int IdCategory { get; set; }
        public int IdTitle { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Title Title { get; set; }
    }
}
