//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCommission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalCommission()
        {
            this.EmployeeVerification = new HashSet<EmployeeVerification>();
        }
    
        public int IdMedicalCommission { get; set; }
        public string MedicalCommissionTitle { get; set; }
        public int IdMedicalCommissionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVerification> EmployeeVerification { get; set; }
        public virtual MedicalCommissionType MedicalCommissionType { get; set; }
    }
}
