//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplomProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vkr_Otdel_KadrovEntities : DbContext
    {
        public vkr_Otdel_KadrovEntities()
            : base("name=vkr_Otdel_KadrovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentType> DepartmentType { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeeStatuses> EmployeeStatuses { get; set; }
        public virtual DbSet<EmployeeStatusType> EmployeeStatusType { get; set; }
        public virtual DbSet<EmployeeVerification> EmployeeVerification { get; set; }
        public virtual DbSet<EmployeeVerificationResult> EmployeeVerificationResult { get; set; }
        public virtual DbSet<HRmanager> HRmanager { get; set; }
        public virtual DbSet<MedicalCommission> MedicalCommission { get; set; }
        public virtual DbSet<MedicalCommissionType> MedicalCommissionType { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<RateType> RateType { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Title> Title { get; set; }
        public virtual DbSet<TypePositions> TypePositions { get; set; }
    }
}
