//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int IdRate { get; set; }
        public decimal TitleRate { get; set; }
        public int IdPositions { get; set; }
        public int IdEmployees { get; set; }
        public int IdRateType { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual RateType RateType { get; set; }
    }
}
